### ISSUE TITLE
Some fixes for games: Alpharay, Pet Rescue, Adventure Park first release

### ISSUE THREAD

**Issue by gyurco** [ishe/plus4#1]
I've debugged some games on the MiST platform, here are the patches I've created to fix them:
~~https://github.com/mist-devel/mist-board/commit/9c444892ad458233a7f355088d208fd28bc328f2#diff-a385f3cf9e422695cb7fedd5d6cc3aa9~~
https://github.com/mist-devel/mist-board/commit/a446f48412455e5aed6321d3c653df514e557d91#diff-a385f3cf9e422695cb7fedd5d6cc3aa9
https://github.com/mist-devel/mist-board/commit/41fc98a704b9323b4c1047e69f6c44a0558479a4#diff-a385f3cf9e422695cb7fedd5d6cc3aa9
https://github.com/mist-devel/mist-board/commit/846f115fc14573a50758392ea3d9efb38b182af5#diff-a385f3cf9e422695cb7fedd5d6cc3aa9

**Comment by ishe** [comment]
Hi,

Thank you for the information and troubleshooting!
Although I have already seen your changes, I have also done troubleshooting
and the videocounter latching condition I have fixed as well when I saw
your solution (which is the same).
The other 3 I have not yet verified. I wanted to spend more time on them to
identify why are these fixes needed.

If you could help me to understand (if you still remember) that would help.

- Ignore test bit.  Why the test bit affects any programs?
- Fix HSP scrolling in Alpharay. This one is the most difficult to
understand what is happening here.
- Fix charpos reload latching (Alpharay bottom line). Changing
VertsubActive to enabledisplay I understand but not sure why
latch_charposition needs to be changed to hpos_392

Thanks anyway for these findings and making ted.v more compatible! I will
merge these results to my line. Recently I am working on the physical TED
replacement so the analog part of the chip.

Thanks
Istvan

PS: What do you use for troubleshooting? Emulator or the Mist?

**Comment by gyurco** [comment]
Hi!
The test bit was accidentally turned on in the first release of Adventure Park, and as the author said, it didn't have any effect, I assume it shouldn't do anything on the real TED. But I couldn't check it myself, as I don't have a Plus/4.
The other patches: they fix Alpharay (the scrolling and the bottom line). Unfortunately I did the debugging 5 month ago, and mostly forgot the details. I've compared plus4 emu internals (I've inserted some trace printfs in the code) with the signal capture on MiST, and these were needed to fix the game.

**Comment by gyurco** [comment]
I believe this one suggested the videocounter reload patch:
https://github.com/istvan-v/plus4emu/blob/master/src/ted_main.cpp#L225

**Comment by ishe** [comment]
Thank you for the information! I will make tests with these software on a
real plus/4 and on the FPGA one.
Usually I debug with plus4emu and logic analyzers (ILA and Open bench logic
sniffer). It takes however time.

**Comment by ishe** [comment]
I have verified some of these issues.
mist-devel/mist-board@a446f48#diff-a385f3cf9e422695cb7fedd5d6cc3aa9 => ok
mist-devel/mist-board@41fc98a#diff-a385f3cf9e422695cb7fedd5d6cc3aa9 => line 654 must stay VertSubActive! Don't change it otherwise it introduces issues (see Epic demo end). Line 637 is ok and itself fixes Alpharay.
Test bit issue is not yet checked. I will investigate  how it works but would not like to remove from code.

**Comment by gyurco** [comment]
Thanks! The VertSubActive change really breaks the Epic demo.
Maybe I've changed it because of the first patch changed the same at another place.
But reverting it now.

Hope you can find out the real meaning of the test bit.
